"""
PalaySense — Lightweight Dashboard Data Loader
==============================================
Reads pre-computed Parquet forecasts and historical data.
NO model training, NO pickle loading, NO heavy computation.
All ML work is done offline via `scripts/run_pipeline.py`.

Defensive design:
- All loaders return empty DataFrames/dicts instead of raising
- Properties guard against empty slices with safe defaults
- Cache invalidation via file mtimes + session upload_refresh_key
"""
import json
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st


# =========================
# PATHS & CONFIG
# =========================
BASE_DIR = Path(__file__).resolve().parent
FORECASTS_DIR = BASE_DIR / "forecasts"
MODELS_DIR = BASE_DIR / "models"

# Legacy fallback paths (for backward compatibility during transition)
LEGACY_DASHBOARD_DIR = BASE_DIR / "Dashboard_Ready"
LEGACY_METRICS_PKL = LEGACY_DASHBOARD_DIR / "metrics.pkl"
LEGACY_MUNICIPAL_FORECASTS_PKL = LEGACY_DASHBOARD_DIR / "municipal_forecasts.pkl"
LEGACY_MODELS_PKL = MODELS_DIR / "municipality_models.pkl"

# Parquet output files (generated by run_pipeline.py)
PROVINCIAL_HISTORY = FORECASTS_DIR / "provincial_history.parquet"
MUNICIPAL_HISTORY = FORECASTS_DIR / "municipal_history.parquet"
SUPPLY_DATA = FORECASTS_DIR / "supply_data.parquet"
PROVINCIAL_FORECASTS = FORECASTS_DIR / "provincial_forecasts.parquet"
MUNICIPAL_FORECASTS = FORECASTS_DIR / "municipal_forecasts.parquet"
MUNICIPAL_FORECASTS_FORWARD = FORECASTS_DIR / "municipal_forecasts_forward.parquet"
METRICS_JSON = FORECASTS_DIR / "metrics.json"
METADATA_JSON = FORECASTS_DIR / "forecast_metadata.json"

# Real per-municipality PRODUCTION volumes (NOT prices). The municipal_history
# parquet holds palay PRICES (₱/kg); production figures come from the Capstone
# "Palay_Production_per_Municipali" sheet.
MUNICIPAL_PRODUCTION_ML = BASE_DIR / "Capstone_Dataset_Cleaned_ML.xlsx"
MUNICIPAL_PRODUCTION_RAW = BASE_DIR / "Capstone_Datasets.xlsx"
_MUNICIPAL_PRODUCTION_SHEET = "Palay_Production_per_Municipali"


# =========================
# CACHE KEY GENERATION
# =========================
def _get_cache_version_key() -> tuple:
    """
    Generate a cache invalidation key based on file modification times.
    The cache invalidates when any Parquet/JSON output file changes.
    """
    files_to_watch = [
        PROVINCIAL_HISTORY,
        MUNICIPAL_HISTORY,
        SUPPLY_DATA,
        PROVINCIAL_FORECASTS,
        MUNICIPAL_FORECASTS,
        MUNICIPAL_FORECASTS_FORWARD,
        METRICS_JSON,
        METADATA_JSON,
    ]

    mtimes = []
    for p in files_to_watch:
        try:
            mtimes.append(p.stat().st_mtime)
        except FileNotFoundError:
            mtimes.append(0)

    # Also include upload_refresh_key from session for manual invalidation
    refresh_key = st.session_state.get("upload_refresh_key", 0)

    return (tuple(mtimes), refresh_key)


# =========================
# SAFE LOADER HELPERS
# =========================
def _safe_read_parquet(path: Path, date_cols: list[str] | None = None) -> pd.DataFrame:
    """Read parquet with graceful fallback to empty DataFrame."""
    if not path.exists():
        return pd.DataFrame()
    try:
        df = pd.read_parquet(path)
        if date_cols:
            for col in date_cols:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors="coerce")
        return df
    except Exception:
        return pd.DataFrame()


def _safe_read_json(path: Path) -> dict:
    """Read JSON with graceful fallback to empty dict."""
    if not path.exists():
        return {}
    try:
        with open(path, "r") as f:
            return json.load(f)
    except Exception:
        return {}


def _safe_load_pickle(path: Path) -> Any:
    """Load pickle with graceful fallback."""
    if not path.exists():
        return None
    try:
        import joblib
        return joblib.load(path)
    except Exception:
        return None


# =========================
# CORE DATA LOADERS (cached with st.cache_data)
# =========================
@st.cache_data(show_spinner="Loading historical data...", max_entries=1)
def load_provincial_history() -> pd.DataFrame:
    """Load cleaned provincial historical data."""
    df = _safe_read_parquet(PROVINCIAL_HISTORY, date_cols=["date"])
    if not df.empty:
        return df
    # Fallback to legacy Excel if Parquet not found
    legacy_path = BASE_DIR / "cleaned" / "provincial_cleaned.xlsx"
    if legacy_path.exists():
        try:
            df = pd.read_excel(legacy_path, engine="openpyxl")
            if "date" in df.columns:
                df["date"] = pd.to_datetime(df["date"], errors="coerce")
            return df
        except Exception:
            pass
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading municipal history...", max_entries=1)
def load_municipal_history() -> pd.DataFrame:
    """Load cleaned municipal historical data."""
    df = _safe_read_parquet(MUNICIPAL_HISTORY, date_cols=["date"])
    if not df.empty:
        return df
    # Fallback
    legacy_path = BASE_DIR / "cleaned" / "municipality_cleaned.xlsx"
    if legacy_path.exists():
        try:
            df = pd.read_excel(legacy_path, engine="openpyxl")
            if "date" in df.columns:
                df["date"] = pd.to_datetime(df["date"], errors="coerce")
            return df
        except Exception:
            pass
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading supply data...", max_entries=1)
def load_supply_data() -> pd.DataFrame:
    """Load supply/demand data."""
    df = _safe_read_parquet(SUPPLY_DATA, date_cols=["date"])
    if not df.empty:
        return df
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading municipal production...", max_entries=1)
def load_municipal_production() -> pd.DataFrame:
    """Load per-municipality palay PRODUCTION (dry/wet season, total, average).

    ``municipality_history`` stores palay PRICES; the Top-5 / production
    rankings must use this authoritative production source instead.
    """
    for path in (MUNICIPAL_PRODUCTION_ML, MUNICIPAL_PRODUCTION_RAW):
        if not path.exists():
            continue
        try:
            df = pd.read_excel(path, sheet_name=_MUNICIPAL_PRODUCTION_SHEET, engine="openpyxl")
            if df is None or getattr(df, "empty", True):
                continue
            df = df.copy()
            df.columns = [str(c).strip() for c in df.columns]
            renames = {
                "Municipality": "municipality", "Year": "year",
                "Dry_Season": "dry_season", "Wet_Season": "wet_season",
                "Palay_Production": "palay_production", "Ave_Production": "ave_production",
            }
            df = df.rename(columns=renames)
            if "date" not in df.columns and "year" in df.columns:
                df["date"] = pd.to_datetime(
                    df["year"].astype(str) + "-12-01", errors="coerce"
                )
            if "date" in df.columns:
                df["date"] = pd.to_datetime(df["date"], errors="coerce")
            return df
        except Exception:
            continue
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading forecasts...", max_entries=1)
def load_provincial_forecasts() -> pd.DataFrame:
    """Load provincial forecasts (fancy, regular, yield)."""
    return _safe_read_parquet(PROVINCIAL_FORECASTS)


@st.cache_data(show_spinner="Loading municipal forecasts...", max_entries=1)
def load_municipal_forecasts() -> pd.DataFrame:
    """Load municipal forecasts (test-period format for UI compatibility)."""
    df = _safe_read_parquet(MUNICIPAL_FORECASTS)
    if not df.empty:
        return df
    # Fallback to legacy pickle
    legacy = _safe_load_pickle(LEGACY_MUNICIPAL_FORECASTS_PKL)
    if isinstance(legacy, pd.DataFrame):
        return legacy
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading municipal forward forecasts...", max_entries=1)
def load_municipal_forward_forecasts() -> pd.DataFrame:
    """Load municipal forward forecasts (true future predictions with month labels)."""
    return _safe_read_parquet(MUNICIPAL_FORECASTS_FORWARD)


@st.cache_data(show_spinner="Loading metrics...", max_entries=1)
def load_metrics() -> dict:
    """Load model performance metrics."""
    metrics = _safe_read_json(METRICS_JSON)
    if metrics:
        return metrics
    # Fallback to legacy pickle
    legacy = _safe_load_pickle(LEGACY_METRICS_PKL)
    if isinstance(legacy, dict):
        return legacy
    return {}


# =========================
# MODEL BENCHMARK TABLE
# =========================
def _safe_metric(value):
    """Return None for NaN/None values, else a float (nice for tables)."""
    if value is None:
        return None
    try:
        f = float(value)
    except (TypeError, ValueError):
        return None
    return None if pd.isna(f) else f


def _metric_mean(d):
    """Pull the mean RMSE out of a walk-forward metric block."""
    return _safe_metric(((d or {}).get("rmse") or {}).get("mean"))


def _beats(model_block, baseline_block):
    """True when the model's mean walk-forward RMSE is lower than the baseline's."""
    model_rmse = _metric_mean(model_block)
    base_rmse = _metric_mean(baseline_block)
    if model_rmse is None or base_rmse is None:
        return None
    return bool(model_rmse < base_rmse)


def build_model_evaluation_frame(metrics: dict) -> pd.DataFrame:
    """Tidy benchmark table: selected model vs Naive / Seasonal Naive baselines.

    Reads the ``baselines`` and ``walk_forward`` blocks that run_pipeline.py now
    writes into metrics.json. Fully defensive — returns an empty frame when the
    new fields are absent (e.g. old metrics.json from a previous run).
    """
    rows = []
    labels = {
        "fancy": "Provincial Fancy Price",
        "regular": "Provincial Regular Price",
        "yield": "Provincial Yield",
    }
    for key, label in labels.items():
        m = metrics.get(key, {})
        if not isinstance(m, dict) or not m.get("walk_forward"):
            continue

        bl = m.get("baselines", {}) or {}
        wf = m.get("walk_forward", {}) or {}
        wf_model = wf.get("model", {}) or {}
        wf_naive = wf.get("naive", {}) or {}
        wf_sn = wf.get("seasonal_naive", {}) or {}

        rows.append({
            "Forecast": label,
            "Model": m.get("model_name", "Unknown"),
            "RMSE (test)": _safe_metric(m.get("rmse")),
            "MAPE % (test)": _safe_metric(m.get("mape")),
            "R² (test)": _safe_metric(m.get("r2")),
            "Bias (train CV)": _safe_metric(m.get("bias")),
            "Naive RMSE (test)": _safe_metric((bl.get("naive") or {}).get("rmse")),
            "Seas. Naive RMSE (test)": _safe_metric((bl.get("seasonal_naive") or {}).get("rmse")),
            "Walk-Forward RMSE": _safe_metric(wf_model.get("rmse", {}).get("mean")),
            "Walk-Forward ±": _safe_metric(wf_model.get("rmse", {}).get("std")),
            "Walk-Forward MAPE %": _safe_metric(wf_model.get("mape", {}).get("mean")),
            "Origins": wf.get("origins"),
            "Beats Naive": _beats(wf_model, wf_naive),
            "Beats Seas. Naive": _beats(wf_model, wf_sn),
        })
    return pd.DataFrame(rows)


@st.cache_data(show_spinner="Loading metadata...", max_entries=1)
def load_metadata() -> dict:
    """Load forecast metadata (generation time, horizons, etc.)."""
    return _safe_read_json(METADATA_JSON)


# =========================
# SAFE ACCESSOR HELPERS
# =========================
def _safe_first_valid(series: pd.Series, default: Any = None) -> Any:
    """Return first non-NaN value or default."""
    if series is None or series.empty:
        return default
    valid = series.dropna()
    return valid.iloc[0] if not valid.empty else default


def _safe_list_from_series(series: pd.Series, max_len: int | None = None) -> list:
    """Convert series to list, dropping NaN, with optional length limit."""
    if series is None or series.empty:
        return []
    vals = series.dropna().tolist()
    return vals[:max_len] if max_len else vals


def _get_last_date_safe(df: pd.DataFrame, date_col: str = "date") -> pd.Timestamp | None:
    """Get max date from dataframe, returning None if empty/invalid."""
    if df is None or df.empty or date_col not in df.columns:
        return None
    dates = pd.to_datetime(df[date_col], errors="coerce").dropna()
    return dates.max() if not dates.empty else None


# =========================
# HIGH-LEVEL ACCESSOR CLASS
# =========================
class DashboardData:
    """
    Lightweight container providing attribute-style access to all dashboard data.
    Mimics the old `_DashboardReady` object but loads data on-demand from Parquet.
    All properties are defensive against empty/missing data.
    """
    __slots__ = (
        "_provincial_df", "_supply_df", "_municipality_df",
        "_municipality_history_df", "_municipal_production_df",
        "_forecast_3months_fancy",
        "_forecast_variety_3months", "_forecast_quarterly_yield",
        "_df_municipal_forecasts", "_municipal_results",
        "_model_name_fancy", "_model_name_regular", "_model_name_yield",
        "_mae_fancy", "_rmse_fancy", "_r2_fancy",
        "_mae_regular", "_rmse_regular", "_r2_regular",
        "_mae_yield", "_rmse_yield", "_r2_yield",
        "_loaded",
    )

    def __init__(self):
        self._loaded = False

    def _ensure_loaded(self):
        """Lazy-load all data on first access."""
        if self._loaded:
            return

        # Load historical data
        self._provincial_df = load_provincial_history()
        self._supply_df = load_supply_data()
        self._municipality_df = load_municipal_history()
        self._municipality_history_df = load_municipal_history()
        self._municipal_production_df = load_municipal_production()

        # Load forecasts from provincial_forecasts parquet.
        # Provincial price forecasts are 6 months; yield is 4 quarters.
        forecasts_df = load_provincial_forecasts()
        if (
            not forecasts_df.empty
            and "forecast_type" in forecasts_df.columns
            and "forecast_value" in forecasts_df.columns
        ):
            fancy = _safe_list_from_series(
                forecasts_df[forecasts_df["forecast_type"] == "fancy"]["forecast_value"],
                max_len=6
            )
            regular = _safe_list_from_series(
                forecasts_df[forecasts_df["forecast_type"] == "regular"]["forecast_value"],
                max_len=6
            )
            yield_fc = _safe_list_from_series(
                forecasts_df[forecasts_df["forecast_type"] == "yield"]["forecast_value"],
                max_len=4
            )
            self._forecast_3months_fancy = fancy
            self._forecast_variety_3months = regular
            self._forecast_quarterly_yield = yield_fc
        else:
            self._forecast_3months_fancy = []
            self._forecast_variety_3months = []
            self._forecast_quarterly_yield = []

        # Municipal forecasts (test-period format for UI)
        self._df_municipal_forecasts = load_municipal_forecasts()

        # Metrics with safe defaults
        metrics = load_metrics()
        self._model_name_fancy = metrics.get("fancy", {}).get("model_name", "Unknown")
        self._model_name_regular = metrics.get("regular", {}).get("model_name", "Unknown")
        self._model_name_yield = metrics.get("yield", {}).get("model_name", "Unknown")
        self._mae_fancy = float(metrics.get("fancy", {}).get("mae", 0.0) or 0.0)
        self._rmse_fancy = float(metrics.get("fancy", {}).get("rmse", 0.0) or 0.0)
        self._r2_fancy = float(metrics.get("fancy", {}).get("r2", 0.0) or 0.0)
        self._mae_regular = float(metrics.get("regular", {}).get("mae", 0.0) or 0.0)
        self._rmse_regular = float(metrics.get("regular", {}).get("rmse", 0.0) or 0.0)
        self._r2_regular = float(metrics.get("regular", {}).get("r2", 0.0) or 0.0)
        self._mae_yield = float(metrics.get("yield", {}).get("mae", 0.0) or 0.0)
        self._rmse_yield = float(metrics.get("yield", {}).get("rmse", 0.0) or 0.0)
        self._r2_yield = float(metrics.get("yield", {}).get("r2", 0.0) or 0.0)

        # Municipal results (not loaded by default to save memory)
        self._municipal_results = {}

        self._loaded = True

    # --- Properties for historical data ---
    @property
    def provincial_df(self) -> pd.DataFrame:
        self._ensure_loaded()
        return self._provincial_df

    @property
    def supply_df(self) -> pd.DataFrame:
        self._ensure_loaded()
        return self._supply_df

    @property
    def municipality_df(self) -> pd.DataFrame:
        self._ensure_loaded()
        return self._municipality_df

    @property
    def municipality_history_df(self) -> pd.DataFrame:
        self._ensure_loaded()
        return self._municipality_history_df

    @property
    def municipal_production_df(self) -> pd.DataFrame:
        """Per-municipality palay PRODUCTION volumes (not prices).

        Authoritative source for Top-5 production rankings / seasonal pies.
        """
        self._ensure_loaded()
        return self._municipal_production_df

    # --- Properties for forecasts (always return list, never raise) ---
    @property
    def forecast_3months_fancy(self) -> list:
        self._ensure_loaded()
        return self._forecast_3months_fancy

    @property
    def forecast_variety_3months(self) -> list:
        self._ensure_loaded()
        return self._forecast_variety_3months

    @property
    def forecast_quarterly_yield(self) -> list:
        self._ensure_loaded()
        return self._forecast_quarterly_yield

    @property
    def df_municipal_forecasts(self) -> pd.DataFrame:
        self._ensure_loaded()
        return self._df_municipal_forecasts

    @property
    def municipal_results(self) -> dict:
        self._ensure_loaded()
        return self._municipal_results

    # --- Properties for metrics ---
    @property
    def model_name_fancy(self) -> str:
        self._ensure_loaded()
        return self._model_name_fancy

    @property
    def model_name_regular(self) -> str:
        self._ensure_loaded()
        return self._model_name_regular

    @property
    def model_name_yield(self) -> str:
        self._ensure_loaded()
        return self._model_name_yield

    @property
    def mae_fancy(self) -> float:
        self._ensure_loaded()
        return self._mae_fancy

    @property
    def rmse_fancy(self) -> float:
        self._ensure_loaded()
        return self._rmse_fancy

    @property
    def r2_fancy(self) -> float:
        self._ensure_loaded()
        return self._r2_fancy

    @property
    def mae_regular(self) -> float:
        self._ensure_loaded()
        return self._mae_regular

    @property
    def rmse_regular(self) -> float:
        self._ensure_loaded()
        return self._rmse_regular

    @property
    def r2_regular(self) -> float:
        self._ensure_loaded()
        return self._r2_regular

    @property
    def mae_yield(self) -> float:
        self._ensure_loaded()
        return self._mae_yield

    @property
    def rmse_yield(self) -> float:
        self._ensure_loaded()
        return self._rmse_yield

    @property
    def r2_yield(self) -> float:
        self._ensure_loaded()
        return self._r2_yield

    # --- Model benchmark table (defense-grade evaluation) ---
    @property
    def model_evaluation(self) -> pd.DataFrame:
        """Tidy benchmark: selected model vs Naive / Seasonal Naive baselines.

        Built from the evaluation blocks the pipeline writes to metrics.json
        (test-window baselines + walk-forward rolling-origin results).
        """
        return build_model_evaluation_frame(load_metrics())

    # --- Safe computed properties for UI ---
    @property
    def has_provincial_data(self) -> bool:
        """True if provincial history has any rows."""
        self._ensure_loaded()
        return not self._provincial_df.empty

    @property
    def has_municipal_data(self) -> bool:
        """True if municipal history has any rows."""
        self._ensure_loaded()
        return not self._municipality_history_df.empty

    @property
    def has_forecasts(self) -> bool:
        """True if any forecast data exists."""
        self._ensure_loaded()
        return bool(self._forecast_3months_fancy or self._forecast_variety_3months or self._forecast_quarterly_yield)

    @property
    def latest_provincial_date(self) -> pd.Timestamp | None:
        """Latest date in provincial data, or None if empty."""
        self._ensure_loaded()
        return _get_last_date_safe(self._provincial_df, "date")

    @property
    def latest_municipal_date(self) -> pd.Timestamp | None:
        """Latest date in municipal data, or None if empty."""
        self._ensure_loaded()
        return _get_last_date_safe(self._municipality_history_df, "date")

    # --- Forecast horizon metadata ---
    @property
    def provincial_forecast_months(self) -> int:
        """Provincial price forecasts are strictly 6 months."""
        return 6

    @property
    def municipal_forecast_months(self) -> int:
        """Municipal/LGU forecasts are strictly 3 months."""
        return 3


# =========================
# PUBLIC API
# =========================
@st.cache_resource(show_spinner=False)
def _get_dashboard_instance(version_key: tuple) -> DashboardData:
    """Cached singleton instance of DashboardData."""
    return DashboardData()


def reload_dashboard_data() -> DashboardData:
    """
    Main entry point for UI pages.
    Returns a DashboardData object with lazy-loaded Parquet data.
    Cache invalidates when Parquet files change or upload_refresh_key changes.
    """
    version_key = _get_cache_version_key()
    return _get_dashboard_instance(version_key)


# Backward compatibility: module-level attribute access
# Allows `from data.Dashboard_Ready import provincial_df` to work
_name_to_attr = {
    "provincial_df": "provincial_df",
    "supply_df": "supply_df",
    "municipality_df": "municipality_df",
    "municipality_history_df": "municipality_history_df",
    "municipal_production_df": "municipal_production_df",
    "forecast_3months_fancy": "forecast_3months_fancy",
    "forecast_variety_3months": "forecast_variety_3months",
    "forecast_quarterly_yield": "forecast_quarterly_yield",
    "df_municipal_forecasts": "df_municipal_forecasts",
    "municipal_results": "municipal_results",
    "model_name_fancy": "model_name_fancy",
    "model_name_regular": "model_name_regular",
    "model_name_yield": "model_name_yield",
    "mae_fancy": "mae_fancy",
    "rmse_fancy": "rmse_fancy",
    "r2_fancy": "r2_fancy",
    "mae_regular": "mae_regular",
    "rmse_regular": "rmse_regular",
    "r2_regular": "r2_regular",
    "mae_yield": "mae_yield",
    "rmse_yield": "rmse_yield",
    "r2_yield": "r2_yield",
}


def __getattr__(name: str) -> Any:
    if name not in _name_to_attr:
        raise AttributeError(f"module {__name__} has no attribute {name}")
    dr = reload_dashboard_data()
    return getattr(dr, _name_to_attr[name])


def __dir__() -> list[str]:
    return list(_name_to_attr.keys()) + ["reload_dashboard_data", "DashboardData"]